-- ReadinessOps Marketplace R1 Native App setup.
-- This script intentionally contains no fixed database name and no caller-rights
-- procedure. It preserves application data across package upgrades.

CREATE APPLICATION ROLE IF NOT EXISTS READINESSOPS_USER;
CREATE APPLICATION ROLE IF NOT EXISTS READINESSOPS_ADMIN;
GRANT APPLICATION ROLE READINESSOPS_USER TO APPLICATION ROLE READINESSOPS_ADMIN;

CREATE SCHEMA IF NOT EXISTS APP_DATA;
CREATE OR ALTER VERSIONED SCHEMA APP_CODE;

GRANT USAGE ON SCHEMA APP_DATA TO APPLICATION ROLE READINESSOPS_USER;
GRANT USAGE ON SCHEMA APP_CODE TO APPLICATION ROLE READINESSOPS_USER;
GRANT USAGE ON SCHEMA APP_CODE TO APPLICATION ROLE READINESSOPS_ADMIN;

CREATE TABLE IF NOT EXISTS APP_DATA.EVIDENCE_SNAPSHOT (
    EVIDENCE_ID         VARCHAR NOT NULL,
    SOURCE_REFERENCE    VARCHAR NOT NULL,
    SOURCE_BINDING_TOKEN VARCHAR NOT NULL,
    SOURCE_KEY_COLUMN   VARCHAR NOT NULL,
    SOURCE_ROW_KEY      VARCHAR NOT NULL,
    TITLE_COLUMN        VARCHAR NOT NULL,
    TEXT_COLUMN         VARCHAR NOT NULL,
    EVIDENCE_TITLE      VARCHAR NOT NULL,
    EVIDENCE_TEXT       VARCHAR NOT NULL,
    CONTENT_SHA256      VARCHAR NOT NULL,
    CAPTURED_AT         TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CAPTURED_BY         VARCHAR NOT NULL DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS APP_DATA.AI_PROPOSAL (
    PROPOSAL_ID         VARCHAR NOT NULL,
    EVIDENCE_ID         VARCHAR NOT NULL,
    PROPOSAL_TYPE       VARCHAR NOT NULL,
    PROPOSAL_TEXT       VARCHAR NOT NULL,
    STATUS              VARCHAR NOT NULL,
    MODEL_NAME          VARCHAR NOT NULL,
    PROMPT_VERSION      VARCHAR NOT NULL,
    CREATED_AT          TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY          VARCHAR NOT NULL DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS APP_DATA.REFERENCE_BINDING_STATE (
    REFERENCE_NAME      VARCHAR NOT NULL,
    BINDING_TOKEN       VARCHAR NOT NULL,
    UPDATED_AT          TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY          VARCHAR NOT NULL DEFAULT CURRENT_USER()
);

CREATE OR REPLACE VIEW APP_CODE.V_EVIDENCE_SNAPSHOT AS
SELECT
    EVIDENCE_ID,
    SOURCE_REFERENCE,
    SOURCE_KEY_COLUMN,
    SOURCE_ROW_KEY,
    EVIDENCE_TITLE,
    CONTENT_SHA256,
    CAPTURED_AT,
    CAPTURED_BY
FROM APP_DATA.EVIDENCE_SNAPSHOT;

CREATE OR REPLACE VIEW APP_CODE.V_REVIEW_REQUIRED_PROPOSAL AS
SELECT
    PROPOSAL_ID,
    EVIDENCE_ID,
    PROPOSAL_TYPE,
    PROPOSAL_TEXT,
    STATUS,
    MODEL_NAME,
    PROMPT_VERSION,
    CREATED_AT,
    CREATED_BY
FROM APP_DATA.AI_PROPOSAL
WHERE STATUS = 'REVIEW_REQUIRED';

GRANT SELECT ON VIEW APP_CODE.V_EVIDENCE_SNAPSHOT
    TO APPLICATION ROLE READINESSOPS_USER;
GRANT SELECT ON VIEW APP_CODE.V_REVIEW_REQUIRED_PROPOSAL
    TO APPLICATION ROLE READINESSOPS_USER;

CREATE OR REPLACE PROCEDURE APP_CODE.REGISTER_SINGLE_REFERENCE(
    REF_NAME STRING,
    OPERATION STRING,
    REF_OR_ALIAS STRING
)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    CASE (OPERATION)
        WHEN 'ADD' THEN
            SELECT SYSTEM$SET_REFERENCE(:REF_NAME, :REF_OR_ALIAS);
            DELETE FROM APP_DATA.REFERENCE_BINDING_STATE
             WHERE REFERENCE_NAME = :REF_NAME;
            INSERT INTO APP_DATA.REFERENCE_BINDING_STATE (
                REFERENCE_NAME,
                BINDING_TOKEN,
                UPDATED_AT,
                UPDATED_BY
            ) VALUES (
                :REF_NAME,
                :REF_OR_ALIAS,
                CURRENT_TIMESTAMP(),
                CURRENT_USER()
            );
        WHEN 'REMOVE' THEN
            SELECT SYSTEM$REMOVE_REFERENCE(:REF_NAME, :REF_OR_ALIAS);
            DELETE FROM APP_DATA.REFERENCE_BINDING_STATE
             WHERE REFERENCE_NAME = :REF_NAME;
        WHEN 'CLEAR' THEN
            SELECT SYSTEM$REMOVE_ALL_REFERENCES(:REF_NAME);
            DELETE FROM APP_DATA.REFERENCE_BINDING_STATE
             WHERE REFERENCE_NAME = :REF_NAME;
        ELSE
            RETURN 'Unknown reference operation: ' || OPERATION;
    END CASE;
    RETURN NULL;
END;
$$;

GRANT USAGE ON PROCEDURE APP_CODE.REGISTER_SINGLE_REFERENCE(
    STRING, STRING, STRING
) TO APPLICATION ROLE READINESSOPS_ADMIN;

CREATE OR REPLACE PROCEDURE APP_CODE.SP_IMPORT_AND_PROPOSE_ONE(
    SOURCE_KIND STRING,
    SOURCE_KEY_COLUMN STRING,
    SOURCE_KEY_VALUE STRING,
    TITLE_COLUMN STRING,
    TEXT_COLUMN STRING
)
RETURNS VARIANT
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
DECLARE
    V_SOURCE_KIND       STRING;
    V_SOURCE_REFERENCE  STRING;
    V_BINDING_TOKEN      STRING;
    V_ROW                OBJECT;
    V_TITLE              STRING;
    V_TEXT               STRING;
    V_CONTENT_SHA256     STRING;
    V_EVIDENCE_ID        STRING;
    V_PROPOSAL_ID        STRING;
    V_PROMPT              STRING;
    V_AI_RESPONSE         STRING;
    V_EXISTING            NUMBER DEFAULT 0;
    V_MATCH_COUNT         NUMBER DEFAULT 0;
BEGIN
    V_SOURCE_KIND := UPPER(TRIM(SOURCE_KIND));

    IF (V_SOURCE_KIND NOT IN ('TABLE', 'VIEW')) THEN
        RETURN OBJECT_CONSTRUCT(
            'status', 'FAILED',
            'error', 'SOURCE_KIND must be TABLE or VIEW.'
        );
    END IF;

    IF (NULLIF(TRIM(SOURCE_KEY_COLUMN), '') IS NULL
        OR NULLIF(TRIM(SOURCE_KEY_VALUE), '') IS NULL
        OR NULLIF(TRIM(TITLE_COLUMN), '') IS NULL
        OR NULLIF(TRIM(TEXT_COLUMN), '') IS NULL) THEN
        RETURN OBJECT_CONSTRUCT(
            'status', 'FAILED',
            'error', 'Column mappings and source key value are required.'
        );
    END IF;

    IF (V_SOURCE_KIND = 'TABLE') THEN
        V_SOURCE_REFERENCE := 'EVIDENCE_SOURCE_TABLE';
        SELECT COUNT(*)
          INTO :V_MATCH_COUNT
          FROM REFERENCE('EVIDENCE_SOURCE_TABLE')
         WHERE TO_VARCHAR(GET_IGNORE_CASE(
                   OBJECT_CONSTRUCT_KEEP_NULL(*), :SOURCE_KEY_COLUMN
               )) = :SOURCE_KEY_VALUE;
    ELSE
        V_SOURCE_REFERENCE := 'EVIDENCE_SOURCE_VIEW';
        SELECT COUNT(*)
          INTO :V_MATCH_COUNT
          FROM REFERENCE('EVIDENCE_SOURCE_VIEW')
         WHERE TO_VARCHAR(GET_IGNORE_CASE(
                   OBJECT_CONSTRUCT_KEEP_NULL(*), :SOURCE_KEY_COLUMN
               )) = :SOURCE_KEY_VALUE;
    END IF;

    IF (V_MATCH_COUNT = 0) THEN
        RETURN OBJECT_CONSTRUCT(
            'status', 'FAILED',
            'error', 'No source row matched the supplied key.'
        );
    ELSEIF (V_MATCH_COUNT > 1) THEN
        RETURN OBJECT_CONSTRUCT(
            'status', 'FAILED',
            'error', 'The supplied source key is not unique.'
        );
    END IF;

    SELECT BINDING_TOKEN
      INTO :V_BINDING_TOKEN
      FROM APP_DATA.REFERENCE_BINDING_STATE
     WHERE REFERENCE_NAME = :V_SOURCE_REFERENCE
     LIMIT 1;

    IF (V_SOURCE_KIND = 'TABLE') THEN
        SELECT OBJECT_CONSTRUCT_KEEP_NULL(*)
          INTO :V_ROW
          FROM REFERENCE('EVIDENCE_SOURCE_TABLE')
         WHERE TO_VARCHAR(GET_IGNORE_CASE(
                   OBJECT_CONSTRUCT_KEEP_NULL(*), :SOURCE_KEY_COLUMN
               )) = :SOURCE_KEY_VALUE
         LIMIT 1;
    ELSE
        SELECT OBJECT_CONSTRUCT_KEEP_NULL(*)
          INTO :V_ROW
          FROM REFERENCE('EVIDENCE_SOURCE_VIEW')
         WHERE TO_VARCHAR(GET_IGNORE_CASE(
                   OBJECT_CONSTRUCT_KEEP_NULL(*), :SOURCE_KEY_COLUMN
               )) = :SOURCE_KEY_VALUE
         LIMIT 1;
    END IF;

    SELECT
        TO_VARCHAR(GET_IGNORE_CASE(:V_ROW, :TITLE_COLUMN)),
        TO_VARCHAR(GET_IGNORE_CASE(:V_ROW, :TEXT_COLUMN))
      INTO :V_TITLE, :V_TEXT;

    IF (NULLIF(TRIM(V_TITLE), '') IS NULL OR NULLIF(TRIM(V_TEXT), '') IS NULL) THEN
        RETURN OBJECT_CONSTRUCT(
            'status', 'FAILED',
            'error', 'The mapped title or evidence text is null or empty.'
        );
    END IF;

    IF (LENGTH(V_TEXT) > 50000) THEN
        RETURN OBJECT_CONSTRUCT(
            'status', 'FAILED',
            'error', 'Evidence text exceeds the R1 limit of 50,000 characters.'
        );
    END IF;

    SELECT SHA2(:V_TEXT, 256) INTO :V_CONTENT_SHA256;
    V_EVIDENCE_ID := 'EV_' || SUBSTR(
        SHA2(V_BINDING_TOKEN || '|' || SOURCE_KEY_COLUMN || '|' ||
             SOURCE_KEY_VALUE || '|' || TITLE_COLUMN || '|' || TEXT_COLUMN || '|' ||
             V_TITLE || '|' || V_CONTENT_SHA256, 256),
        1,
        32
    );
    V_PROPOSAL_ID := 'PROP_' || SUBSTR(
        SHA2(V_EVIDENCE_ID || '|R1_EVIDENCE_REVIEW_V1', 256), 1, 32
    );

    SELECT COUNT(*)
      INTO :V_EXISTING
      FROM APP_DATA.AI_PROPOSAL
     WHERE PROPOSAL_ID = :V_PROPOSAL_ID;

    IF (V_EXISTING > 0) THEN
        RETURN OBJECT_CONSTRUCT(
            'status', 'SKIPPED',
            'reason', 'An unchanged source row already has a review-required proposal.',
            'evidence_id', V_EVIDENCE_ID,
            'proposal_id', V_PROPOSAL_ID
        );
    END IF;

    V_PROMPT :=
        'You are ReadinessOps. Review the supplied evidence and produce a concise ' ||
        'decision-support proposal. State the evidence-backed observation, the gap ' ||
        'or risk, and the next human decision required. Do not claim approval, ' ||
        'publication, or completion. Evidence title: ' || V_TITLE ||
        '\nEvidence text:\n' || V_TEXT;

    BEGIN TRANSACTION;

    INSERT INTO APP_DATA.EVIDENCE_SNAPSHOT (
        EVIDENCE_ID,
        SOURCE_REFERENCE,
        SOURCE_BINDING_TOKEN,
        SOURCE_KEY_COLUMN,
        SOURCE_ROW_KEY,
        TITLE_COLUMN,
        TEXT_COLUMN,
        EVIDENCE_TITLE,
        EVIDENCE_TEXT,
        CONTENT_SHA256,
        CAPTURED_AT,
        CAPTURED_BY
    )
    SELECT
        :V_EVIDENCE_ID,
        :V_SOURCE_REFERENCE,
        :V_BINDING_TOKEN,
        :SOURCE_KEY_COLUMN,
        :SOURCE_KEY_VALUE,
        :TITLE_COLUMN,
        :TEXT_COLUMN,
        :V_TITLE,
        :V_TEXT,
        :V_CONTENT_SHA256,
        CURRENT_TIMESTAMP(),
        CURRENT_USER()
    WHERE NOT EXISTS (
        SELECT 1
          FROM APP_DATA.EVIDENCE_SNAPSHOT
         WHERE EVIDENCE_ID = :V_EVIDENCE_ID
           AND SOURCE_REFERENCE = :V_SOURCE_REFERENCE
           AND SOURCE_BINDING_TOKEN = :V_BINDING_TOKEN
           AND SOURCE_ROW_KEY = :SOURCE_KEY_VALUE
    );

    SELECT SNOWFLAKE.CORTEX.AI_COMPLETE('mistral-large2', :V_PROMPT)
      INTO :V_AI_RESPONSE;

    INSERT INTO APP_DATA.AI_PROPOSAL (
        PROPOSAL_ID,
        EVIDENCE_ID,
        PROPOSAL_TYPE,
        PROPOSAL_TEXT,
        STATUS,
        MODEL_NAME,
        PROMPT_VERSION,
        CREATED_AT,
        CREATED_BY
    ) VALUES (
        :V_PROPOSAL_ID,
        :V_EVIDENCE_ID,
        'EVIDENCE_REVIEW',
        :V_AI_RESPONSE,
        'REVIEW_REQUIRED',
        'mistral-large2',
        'R1_EVIDENCE_REVIEW_V1',
        CURRENT_TIMESTAMP(),
        CURRENT_USER()
    );

    COMMIT;

    RETURN OBJECT_CONSTRUCT(
        'status', 'REVIEW_REQUIRED',
        'evidence_id', V_EVIDENCE_ID,
        'proposal_id', V_PROPOSAL_ID,
        'model', 'mistral-large2',
        'human_gate', 'Approval and publication are not performed by this procedure.'
    );
END;
$$;

GRANT USAGE ON PROCEDURE APP_CODE.SP_IMPORT_AND_PROPOSE_ONE(
    STRING, STRING, STRING, STRING, STRING
) TO APPLICATION ROLE READINESSOPS_ADMIN;

CREATE STREAMLIT IF NOT EXISTS APP_CODE.READINESSOPS
    FROM '/streamlit'
    MAIN_FILE = '/readinessops_native.py';

GRANT USAGE ON STREAMLIT APP_CODE.READINESSOPS
    TO APPLICATION ROLE READINESSOPS_ADMIN;
