-- ReadinessOps Marketplace Native App setup.
-- This package ports the existing governed ReadinessOps data model and
-- four-section Decision Pack into the Native App boundary. It does not create a
-- separate product model and it never approves or publishes AI output.

CREATE APPLICATION ROLE IF NOT EXISTS READINESSOPS_USER;
CREATE APPLICATION ROLE IF NOT EXISTS READINESSOPS_ADMIN;
GRANT APPLICATION ROLE READINESSOPS_USER TO APPLICATION ROLE READINESSOPS_ADMIN;

CREATE SCHEMA IF NOT EXISTS APP_DATA;
CREATE OR ALTER VERSIONED SCHEMA APP_CODE;

GRANT USAGE ON SCHEMA APP_DATA TO APPLICATION ROLE READINESSOPS_USER;
GRANT USAGE ON SCHEMA APP_CODE TO APPLICATION ROLE READINESSOPS_USER;
GRANT USAGE ON SCHEMA APP_CODE TO APPLICATION ROLE READINESSOPS_ADMIN;

-- Existing ReadinessOps model, qualified for an install-local persistent schema.
CREATE TABLE IF NOT EXISTS APP_DATA.ASSESSMENT_RUNS (
    RUN_ID VARCHAR,
    RUN_NAME VARCHAR,
    ORGANIZATION_NAME VARCHAR,
    ASSESSMENT_SCOPE VARCHAR,
    STATUS VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INITIATIVE_ID VARCHAR
);

CREATE TABLE IF NOT EXISTS APP_DATA.READINESS_DOMAINS (
    DOMAIN_ID VARCHAR,
    DOMAIN_NAME VARCHAR,
    DOMAIN_DESCRIPTION VARCHAR,
    SORT_ORDER NUMBER
);

CREATE TABLE IF NOT EXISTS APP_DATA.READINESS_QUESTIONS (
    QUESTION_ID VARCHAR,
    DOMAIN_ID VARCHAR,
    QUESTION_TEXT VARCHAR,
    EXPECTED_EVIDENCE VARCHAR,
    WEIGHT NUMBER,
    SORT_ORDER NUMBER
);

CREATE TABLE IF NOT EXISTS APP_DATA.ASSESSMENT_ANSWERS (
    RUN_ID VARCHAR,
    QUESTION_ID VARCHAR,
    ANSWER_STATUS VARCHAR,
    ANSWER_TEXT VARCHAR,
    OWNER_NAME VARCHAR,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_DATA.AI_INITIATIVE (
    INITIATIVE_ID VARCHAR NOT NULL,
    INITIATIVE_NAME VARCHAR NOT NULL,
    DESCRIPTION VARCHAR,
    OWNER_NAME VARCHAR,
    LIFECYCLE_STAGE VARCHAR DEFAULT 'IDEATION',
    BUSINESS_OUTCOME VARCHAR,
    STATUS VARCHAR DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR DEFAULT CURRENT_USER(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY VARCHAR DEFAULT CURRENT_USER()
);

CREATE TABLE IF NOT EXISTS APP_DATA.EVIDENCE_ITEMS (
    EVIDENCE_ID VARCHAR,
    RUN_ID VARCHAR,
    QUESTION_ID VARCHAR,
    EVIDENCE_TITLE VARCHAR,
    EVIDENCE_TEXT VARCHAR,
    EVIDENCE_STATUS VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILENAME VARCHAR,
    SOURCE_TYPE VARCHAR,
    MEDIA_TYPE VARCHAR,
    CONTENT_SHA256 VARCHAR,
    BYTE_COUNT NUMBER,
    CHAR_COUNT NUMBER,
    UPLOADED_AT TIMESTAMP_NTZ,
    UPLOADED_BY VARCHAR,
    STAGE_PATH VARCHAR,
    PARSER_NAME VARCHAR,
    PAGE_COUNT NUMBER,
    SOURCE_REFERENCE VARCHAR,
    SOURCE_BINDING_TOKEN VARCHAR,
    SOURCE_KEY_COLUMN VARCHAR,
    SOURCE_ROW_KEY VARCHAR,
    TITLE_COLUMN VARCHAR,
    TEXT_COLUMN VARCHAR
);

CREATE TABLE IF NOT EXISTS APP_DATA.GOVERNANCE_AGENT_RUN (
    AGENT_RUN_ID VARCHAR NOT NULL,
    ASSESSMENT_RUN_ID VARCHAR NOT NULL,
    WORKFLOW_TYPE VARCHAR DEFAULT 'FULL_GOVERNANCE_REVIEW',
    STANDARD_INSTRUCTION VARCHAR,
    ADDITIONAL_INSTRUCTION VARCHAR,
    STATUS VARCHAR DEFAULT 'RUNNING',
    STARTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT TIMESTAMP_NTZ,
    MODEL_NAME VARCHAR,
    PROMPT_VERSION VARCHAR DEFAULT '1.0',
    RULESET_VERSION VARCHAR DEFAULT '1.0',
    INPUT_FINGERPRINT VARCHAR,
    SUMMARY VARCHAR,
    ERROR_MESSAGE VARCHAR,
    CREATED_BY VARCHAR DEFAULT CURRENT_USER(),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_DATA.GOVERNANCE_AGENT_PROPOSAL (
    PROPOSAL_ID VARCHAR NOT NULL,
    AGENT_RUN_ID VARCHAR NOT NULL,
    ASSESSMENT_RUN_ID VARCHAR NOT NULL,
    PROPOSAL_TYPE VARCHAR NOT NULL,
    TITLE VARCHAR,
    DESCRIPTION VARCHAR,
    SEVERITY VARCHAR,
    PRIORITY NUMBER,
    RATIONALE VARCHAR,
    RECOMMENDED_OWNER VARCHAR,
    RECOMMENDED_DUE_DATE NUMBER,
    STATUS VARCHAR DEFAULT 'REVIEW_REQUIRED',
    REVIEW_COMMENT VARCHAR,
    REVIEWED_BY VARCHAR,
    REVIEWED_AT TIMESTAMP_NTZ,
    PUBLISHED_ENTITY_ID VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PROPOSAL_PAYLOAD VARIANT
);

CREATE TABLE IF NOT EXISTS APP_DATA.GOVERNANCE_AGENT_PROPOSAL_SOURCE (
    PROPOSAL_SOURCE_ID VARCHAR NOT NULL,
    PROPOSAL_ID VARCHAR NOT NULL,
    SOURCE_TYPE VARCHAR,
    SOURCE_ID VARCHAR,
    QUESTION_ID VARCHAR,
    ANSWER_TEXT VARCHAR,
    EVIDENCE_ITEM_ID VARCHAR,
    RULE_ID VARCHAR,
    RULE_VERSION VARCHAR,
    SOURCE_SUMMARY VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_DATA.GOVERNANCE_APPROVAL_HISTORY (
    APPROVAL_HISTORY_ID VARCHAR NOT NULL,
    PROPOSAL_ID VARCHAR NOT NULL,
    ACTION_TYPE VARCHAR NOT NULL,
    PREVIOUS_STATUS VARCHAR,
    NEW_STATUS VARCHAR,
    COMMENT VARCHAR,
    ACTED_BY VARCHAR DEFAULT CURRENT_USER(),
    ACTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_DATA.GOVERNANCE_AGENT_RUN_STEP (
    AGENT_RUN_STEP_ID VARCHAR NOT NULL,
    AGENT_RUN_ID VARCHAR NOT NULL,
    STEP_SEQUENCE NUMBER NOT NULL,
    STEP_CODE VARCHAR NOT NULL,
    STEP_NAME VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    STARTED_AT TIMESTAMP_NTZ NOT NULL,
    COMPLETED_AT TIMESTAMP_NTZ,
    DURATION_MS NUMBER,
    STEP_DETAIL VARIANT,
    ERROR_MESSAGE VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_DATA.GOVERNED_DECISION_RECORD (
    DECISION_RECORD_ID VARCHAR NOT NULL,
    SOURCE_PROPOSAL_ID VARCHAR NOT NULL,
    SOURCE_AGENT_RUN_ID VARCHAR NOT NULL,
    ASSESSMENT_RUN_ID VARCHAR NOT NULL,
    INITIATIVE_ID VARCHAR,
    DECISION_TYPE VARCHAR NOT NULL,
    TITLE VARCHAR,
    DESCRIPTION VARCHAR,
    DECISION_PAYLOAD VARIANT NOT NULL,
    PUBLISHED_BY VARCHAR DEFAULT CURRENT_USER(),
    PUBLISHED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS APP_DATA.REFERENCE_BINDING_STATE (
    REFERENCE_NAME VARCHAR NOT NULL,
    BINDING_TOKEN VARCHAR NOT NULL,
    UPDATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_BY VARCHAR DEFAULT CURRENT_USER()
);

-- Existing ReadinessOps presentation contracts over install-local state.
CREATE OR REPLACE VIEW APP_CODE.V_ASSESSMENT_CONTEXT AS
SELECT
    r.RUN_ID,
    r.RUN_NAME,
    r.ORGANIZATION_NAME,
    r.ASSESSMENT_SCOPE,
    r.STATUS,
    r.CREATED_AT,
    r.INITIATIVE_ID,
    i.INITIATIVE_NAME,
    i.DESCRIPTION AS INITIATIVE_DESCRIPTION,
    i.OWNER_NAME,
    i.LIFECYCLE_STAGE,
    i.BUSINESS_OUTCOME
FROM APP_DATA.ASSESSMENT_RUNS r
LEFT JOIN APP_DATA.AI_INITIATIVE i
    ON i.INITIATIVE_ID = r.INITIATIVE_ID;

CREATE OR REPLACE VIEW APP_CODE.V_EVIDENCE_ITEMS AS
SELECT
    EVIDENCE_ID,
    RUN_ID,
    QUESTION_ID,
    EVIDENCE_TITLE,
    EVIDENCE_TEXT,
    EVIDENCE_STATUS,
    SOURCE_TYPE,
    CONTENT_SHA256,
    SOURCE_REFERENCE,
    SOURCE_KEY_COLUMN,
    SOURCE_ROW_KEY,
    CREATED_AT,
    UPLOADED_AT,
    UPLOADED_BY
FROM APP_DATA.EVIDENCE_ITEMS;

CREATE OR REPLACE VIEW APP_CODE.V_DECISION_PACK_REVIEW AS
SELECT
    p.PROPOSAL_ID,
    p.AGENT_RUN_ID,
    p.ASSESSMENT_RUN_ID,
    p.PROPOSAL_TYPE,
    p.TITLE,
    p.DESCRIPTION,
    p.SEVERITY,
    p.PRIORITY,
    p.RATIONALE,
    p.STATUS,
    p.PROPOSAL_PAYLOAD,
    p.CREATED_AT,
    p.UPDATED_AT
FROM APP_DATA.GOVERNANCE_AGENT_PROPOSAL p
WHERE p.PROPOSAL_TYPE IN (
    'DECISION_GOVERNANCE',
    'DECISION_VALUE',
    'DECISION_MODEL_ROUTING',
    'DECISION_PORTFOLIO'
);

CREATE OR REPLACE VIEW APP_CODE.V_AGENT_RUN_STEP AS
SELECT
    s.AGENT_RUN_ID,
    r.ASSESSMENT_RUN_ID,
    s.STEP_SEQUENCE,
    s.STEP_CODE,
    s.STEP_NAME,
    s.STATUS,
    s.STARTED_AT,
    s.COMPLETED_AT,
    s.DURATION_MS,
    s.STEP_DETAIL,
    s.ERROR_MESSAGE
FROM APP_DATA.GOVERNANCE_AGENT_RUN_STEP s
JOIN APP_DATA.GOVERNANCE_AGENT_RUN r
    ON r.AGENT_RUN_ID = s.AGENT_RUN_ID;

GRANT SELECT ON VIEW APP_CODE.V_ASSESSMENT_CONTEXT
    TO APPLICATION ROLE READINESSOPS_USER;
GRANT SELECT ON VIEW APP_CODE.V_EVIDENCE_ITEMS
    TO APPLICATION ROLE READINESSOPS_USER;
GRANT SELECT ON VIEW APP_CODE.V_DECISION_PACK_REVIEW
    TO APPLICATION ROLE READINESSOPS_USER;
GRANT SELECT ON VIEW APP_CODE.V_AGENT_RUN_STEP
    TO APPLICATION ROLE READINESSOPS_USER;

-- Reference callback used by Snowflake's consumer consent flow.
CREATE OR REPLACE PROCEDURE APP_CODE.REGISTER_SINGLE_REFERENCE(
    REF_NAME STRING,
    OPERATION STRING,
    REF_OR_ALIAS STRING
)
RETURNS STRING
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    CASE (OPERATION)
        WHEN 'ADD' THEN
            SELECT SYSTEM$SET_REFERENCE(:REF_NAME, :REF_OR_ALIAS);
            DELETE FROM APP_DATA.REFERENCE_BINDING_STATE
             WHERE REFERENCE_NAME = :REF_NAME;
            INSERT INTO APP_DATA.REFERENCE_BINDING_STATE (
                REFERENCE_NAME,
                BINDING_TOKEN,
                UPDATED_AT,
                UPDATED_BY
            ) VALUES (
                :REF_NAME,
                :REF_OR_ALIAS,
                CURRENT_TIMESTAMP(),
                CURRENT_USER()
            );
        WHEN 'REMOVE' THEN
            SELECT SYSTEM$REMOVE_REFERENCE(:REF_NAME, :REF_OR_ALIAS);
            DELETE FROM APP_DATA.REFERENCE_BINDING_STATE
             WHERE REFERENCE_NAME = :REF_NAME;
        WHEN 'CLEAR' THEN
            SELECT SYSTEM$REMOVE_ALL_REFERENCES(:REF_NAME);
            DELETE FROM APP_DATA.REFERENCE_BINDING_STATE
             WHERE REFERENCE_NAME = :REF_NAME;
        ELSE
            RETURN 'Unknown reference operation: ' || OPERATION;
    END CASE;
    RETURN NULL;
END;
$$;

GRANT USAGE ON PROCEDURE APP_CODE.REGISTER_SINGLE_REFERENCE(
    STRING, STRING, STRING
) TO APPLICATION ROLE READINESSOPS_ADMIN;

-- Modular Native App adaptations of the existing ingestion and Decision Pack.
EXECUTE IMMEDIATE FROM '/sql/import_reference_evidence.sql';
EXECUTE IMMEDIATE FROM '/sql/decision_pack.sql';

CREATE STREAMLIT IF NOT EXISTS APP_CODE.READINESSOPS
    FROM '/streamlit'
    MAIN_FILE = '/readinessops_native.py';

GRANT USAGE ON STREAMLIT APP_CODE.READINESSOPS
    TO APPLICATION ROLE READINESSOPS_ADMIN;
