-- ReadinessOps Marketplace R1 isolated runtime-test preparation.
-- Run only in the designated development account as ACCOUNTADMIN.
-- This grants the two privileges declared by the Native App manifest and
-- creates one reversible consumer-owned evidence table for reference testing.

GRANT READ SESSION ON ACCOUNT
    TO APPLICATION READINESSOPS_MARKETPLACE_DEV;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER
    TO APPLICATION READINESSOPS_MARKETPLACE_DEV;

GRANT APPLICATION ROLE READINESSOPS_MARKETPLACE_DEV.READINESSOPS_ADMIN
    TO ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS READINESSOPS_NATIVE_APP_TEST;
CREATE SCHEMA IF NOT EXISTS READINESSOPS_NATIVE_APP_TEST.PUBLIC;

CREATE TABLE IF NOT EXISTS
    READINESSOPS_NATIVE_APP_TEST.PUBLIC.EVIDENCE_SOURCE (
        EVIDENCE_ID VARCHAR NOT NULL,
        EVIDENCE_TITLE VARCHAR NOT NULL,
        EVIDENCE_TEXT VARCHAR NOT NULL
    );

MERGE INTO READINESSOPS_NATIVE_APP_TEST.PUBLIC.EVIDENCE_SOURCE AS target
USING (
    SELECT
        'EV-001' AS EVIDENCE_ID,
        'R1 Native App runtime evidence' AS EVIDENCE_TITLE,
        'Human review and explicit publication remain required. AI output must remain a review-required proposal.' AS EVIDENCE_TEXT
) AS source
ON target.EVIDENCE_ID = source.EVIDENCE_ID
WHEN MATCHED THEN UPDATE SET
    EVIDENCE_TITLE = source.EVIDENCE_TITLE,
    EVIDENCE_TEXT = source.EVIDENCE_TEXT
WHEN NOT MATCHED THEN INSERT (
    EVIDENCE_ID,
    EVIDENCE_TITLE,
    EVIDENCE_TEXT
) VALUES (
    source.EVIDENCE_ID,
    source.EVIDENCE_TITLE,
    source.EVIDENCE_TEXT
);

SHOW PRIVILEGES IN APPLICATION READINESSOPS_MARKETPLACE_DEV;

SELECT EVIDENCE_ID, EVIDENCE_TITLE, EVIDENCE_TEXT
FROM READINESSOPS_NATIVE_APP_TEST.PUBLIC.EVIDENCE_SOURCE
ORDER BY EVIDENCE_ID;
