-- ============================================================
-- Governance Agent Data Model
-- ============================================================
-- Adds governed draft-review-publish lifecycle tables.
-- Does not modify existing table structures except adding
-- optional traceability columns to READINESS_GAPS and
-- RECOMMENDED_ACTIONS.
-- ============================================================

USE SCHEMA READINESSOPS_VALIDATION.APP;

-- ============================================================
-- A. GOVERNANCE_AGENT_RUN
-- One record per Full Governance Review execution.
-- ============================================================
CREATE TABLE IF NOT EXISTS GOVERNANCE_AGENT_RUN (
    AGENT_RUN_ID VARCHAR(16777216) NOT NULL,
    ASSESSMENT_RUN_ID VARCHAR(16777216) NOT NULL,
    WORKFLOW_TYPE VARCHAR(100) DEFAULT 'FULL_GOVERNANCE_REVIEW',
    STANDARD_INSTRUCTION VARCHAR(16777216),
    ADDITIONAL_INSTRUCTION VARCHAR(16777216),
    STATUS VARCHAR(50) DEFAULT 'RUNNING',
    STARTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT TIMESTAMP_NTZ(9),
    MODEL_NAME VARCHAR(200),
    PROMPT_VERSION VARCHAR(50) DEFAULT '1.0',
    RULESET_VERSION VARCHAR(50) DEFAULT '1.0',
    INPUT_FINGERPRINT VARCHAR(64),
    SUMMARY VARCHAR(16777216),
    ERROR_MESSAGE VARCHAR(16777216),
    CREATED_BY VARCHAR(200) DEFAULT CURRENT_USER(),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- B. GOVERNANCE_AGENT_PROPOSAL
-- One record per proposed Gap, Risk, or Action.
-- ============================================================
CREATE TABLE IF NOT EXISTS GOVERNANCE_AGENT_PROPOSAL (
    PROPOSAL_ID VARCHAR(16777216) NOT NULL,
    AGENT_RUN_ID VARCHAR(16777216) NOT NULL,
    ASSESSMENT_RUN_ID VARCHAR(16777216) NOT NULL,
    PROPOSAL_TYPE VARCHAR(50) NOT NULL,
    TITLE VARCHAR(16777216),
    DESCRIPTION VARCHAR(16777216),
    SEVERITY VARCHAR(50),
    PRIORITY NUMBER(38,0),
    RATIONALE VARCHAR(16777216),
    RECOMMENDED_OWNER VARCHAR(200),
    RECOMMENDED_DUE_DATE NUMBER(38,0),
    STATUS VARCHAR(50) DEFAULT 'REVIEW_REQUIRED',
    REVIEW_COMMENT VARCHAR(16777216),
    REVIEWED_BY VARCHAR(200),
    REVIEWED_AT TIMESTAMP_NTZ(9),
    PUBLISHED_ENTITY_ID VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- C. GOVERNANCE_AGENT_PROPOSAL_SOURCE
-- Traceability between a proposal and its sources.
-- ============================================================
CREATE TABLE IF NOT EXISTS GOVERNANCE_AGENT_PROPOSAL_SOURCE (
    PROPOSAL_SOURCE_ID VARCHAR(16777216) NOT NULL,
    PROPOSAL_ID VARCHAR(16777216) NOT NULL,
    SOURCE_TYPE VARCHAR(100),
    SOURCE_ID VARCHAR(16777216),
    QUESTION_ID VARCHAR(16777216),
    ANSWER_TEXT VARCHAR(16777216),
    EVIDENCE_ITEM_ID VARCHAR(16777216),
    RULE_ID VARCHAR(16777216),
    RULE_VERSION VARCHAR(50),
    SOURCE_SUMMARY VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- D. GOVERNANCE_APPROVAL_HISTORY
-- Immutable review and publication history.
-- ============================================================
CREATE TABLE IF NOT EXISTS GOVERNANCE_APPROVAL_HISTORY (
    APPROVAL_HISTORY_ID VARCHAR(16777216) NOT NULL,
    PROPOSAL_ID VARCHAR(16777216) NOT NULL,
    ACTION_TYPE VARCHAR(50) NOT NULL,
    PREVIOUS_STATUS VARCHAR(50),
    NEW_STATUS VARCHAR(50),
    COMMENT VARCHAR(16777216),
    ACTED_BY VARCHAR(200) DEFAULT CURRENT_USER(),
    ACTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- E. Add traceability columns to existing canonical tables
-- ============================================================
ALTER TABLE READINESS_GAPS ADD COLUMN IF NOT EXISTS SOURCE_PROPOSAL_ID VARCHAR(16777216);
ALTER TABLE READINESS_GAPS ADD COLUMN IF NOT EXISTS SOURCE_AGENT_RUN_ID VARCHAR(16777216);

ALTER TABLE RECOMMENDED_ACTIONS ADD COLUMN IF NOT EXISTS SOURCE_PROPOSAL_ID VARCHAR(16777216);
ALTER TABLE RECOMMENDED_ACTIONS ADD COLUMN IF NOT EXISTS SOURCE_AGENT_RUN_ID VARCHAR(16777216);
