-- ============================================================
-- READINESSOPS View: Action Board
-- ============================================================
-- Denormalized view joining all assessment data for presentation.
-- Exact replica of the deployed V_READINESSOPS_ACTION_BOARD.
-- ============================================================

USE DATABASE READINESSOPS_VALIDATION;
USE SCHEMA APP;

CREATE OR REPLACE VIEW V_READINESSOPS_ACTION_BOARD AS
SELECT
  r.RUN_ID,
  r.RUN_NAME,
  r.ORGANIZATION_NAME,
  d.DOMAIN_NAME,
  q.QUESTION_ID,
  q.QUESTION_TEXT,
  a.ANSWER_STATUS,
  e.EVIDENCE_TITLE,
  e.EVIDENCE_STATUS,
  g.GAP_ID,
  g.SEVERITY,
  g.PRIORITY_SCORE,
  g.GAP_TITLE,
  g.GAP_DESCRIPTION,
  act.ACTION_ID,
  act.ACTION_TITLE,
  act.ACTION_DESCRIPTION,
  act.OWNER_NAME,
  act.DUE_IN_DAYS,
  act.ACTION_STATUS,
  act.CREATED_AT AS ACTION_CREATED_AT
FROM ASSESSMENT_RUNS r
JOIN ASSESSMENT_ANSWERS a
  ON r.RUN_ID = a.RUN_ID
JOIN READINESS_QUESTIONS q
  ON a.QUESTION_ID = q.QUESTION_ID
JOIN READINESS_DOMAINS d
  ON q.DOMAIN_ID = d.DOMAIN_ID
LEFT JOIN EVIDENCE_ITEMS e
  ON r.RUN_ID = e.RUN_ID
 AND q.QUESTION_ID = e.QUESTION_ID
LEFT JOIN READINESS_GAPS g
  ON r.RUN_ID = g.RUN_ID
 AND q.QUESTION_ID = g.QUESTION_ID
 AND g.GAP_ID NOT LIKE 'AR_%'
LEFT JOIN (
  SELECT
    act.*,
    COALESCE(g2.QUESTION_ID, p.QUESTION_ID) AS ACTION_QUESTION_ID
  FROM RECOMMENDED_ACTIONS act
  LEFT JOIN READINESS_GAPS g2
    ON act.GAP_ID = g2.GAP_ID
  LEFT JOIN GOVERNANCE_AGENT_PROPOSAL p
    ON act.SOURCE_PROPOSAL_ID = p.PROPOSAL_ID
  WHERE act.ACTION_ID NOT LIKE 'AR_%'
) act
  ON r.RUN_ID = act.RUN_ID
 AND q.QUESTION_ID = act.ACTION_QUESTION_ID;