-- ============================================================
-- GOVERNANCE AGENT VALIDATION SCRIPT
-- ============================================================
-- Run this script in sequence to validate all governance features.
-- Use: snow sql -f sql/15_validation_tests.sql --connection <conn>
-- ============================================================

USE SCHEMA READINESSOPS_VALIDATION.APP;

-- Deploy updated dashboard view
CREATE OR REPLACE VIEW V_READINESSOPS_ACTION_BOARD AS
SELECT r.RUN_ID, r.RUN_NAME, r.ORGANIZATION_NAME, d.DOMAIN_NAME,
  q.QUESTION_ID, q.QUESTION_TEXT, a.ANSWER_STATUS,
  e.EVIDENCE_TITLE, e.EVIDENCE_STATUS, g.GAP_ID, g.SEVERITY,
  g.PRIORITY_SCORE, g.GAP_TITLE, g.GAP_DESCRIPTION, act.ACTION_ID,
  act.ACTION_TITLE, act.ACTION_DESCRIPTION, act.OWNER_NAME,
  act.DUE_IN_DAYS, act.ACTION_STATUS, act.CREATED_AT AS ACTION_CREATED_AT
FROM ASSESSMENT_RUNS r
JOIN ASSESSMENT_ANSWERS a ON r.RUN_ID = a.RUN_ID
JOIN READINESS_QUESTIONS q ON a.QUESTION_ID = q.QUESTION_ID
JOIN READINESS_DOMAINS d ON q.DOMAIN_ID = d.DOMAIN_ID
LEFT JOIN EVIDENCE_ITEMS e ON r.RUN_ID = e.RUN_ID AND q.QUESTION_ID = e.QUESTION_ID
LEFT JOIN READINESS_GAPS g ON r.RUN_ID = g.RUN_ID AND q.QUESTION_ID = g.QUESTION_ID AND g.GAP_ID NOT LIKE 'AR_%'
LEFT JOIN RECOMMENDED_ACTIONS act ON r.RUN_ID = act.RUN_ID AND g.GAP_ID = act.GAP_ID AND act.ACTION_ID NOT LIKE 'AR_%';

-- TEST 1: Draft isolation
SELECT '--- TEST 1: DRAFT ISOLATION ---' AS TEST;
SELECT 'Proposals in REVIEW_REQUIRED' AS CHECK_NAME, COUNT(*) AS N FROM GOVERNANCE_AGENT_PROPOSAL WHERE STATUS = 'REVIEW_REQUIRED';
SELECT 'Dashboard gap count (should exclude AR_%)' AS CHECK_NAME, COUNT(DISTINCT GAP_ID) AS N FROM V_READINESSOPS_ACTION_BOARD WHERE GAP_ID IS NOT NULL;

-- TEST 2: Source traceability
SELECT '--- TEST 2: SOURCE TRACEABILITY ---' AS TEST;
SELECT p.PROPOSAL_ID, p.TITLE, s.QUESTION_ID, s.SOURCE_SUMMARY
FROM GOVERNANCE_AGENT_PROPOSAL p
JOIN GOVERNANCE_AGENT_PROPOSAL_SOURCE s ON p.PROPOSAL_ID = s.PROPOSAL_ID
WHERE p.PROPOSAL_TYPE = 'GAP'
LIMIT 3;

-- TEST 3: Individual review
SELECT '--- TEST 3: INDIVIDUAL REVIEW ---' AS TEST;
-- Approve first gap, first risk, first action
CALL SP_REVIEW_AGENT_PROPOSAL((SELECT PROPOSAL_ID FROM GOVERNANCE_AGENT_PROPOSAL WHERE PROPOSAL_TYPE = 'GAP' AND STATUS = 'REVIEW_REQUIRED' LIMIT 1), 'APPROVE', 'Test approval');
CALL SP_REVIEW_AGENT_PROPOSAL((SELECT PROPOSAL_ID FROM GOVERNANCE_AGENT_PROPOSAL WHERE PROPOSAL_TYPE = 'RISK' AND STATUS = 'REVIEW_REQUIRED' LIMIT 1), 'APPROVE', 'Test approval');
CALL SP_REVIEW_AGENT_PROPOSAL((SELECT PROPOSAL_ID FROM GOVERNANCE_AGENT_PROPOSAL WHERE PROPOSAL_TYPE = 'ACTION' AND STATUS = 'REVIEW_REQUIRED' LIMIT 1), 'APPROVE', 'Test approval');
-- Reject one proposal
CALL SP_REVIEW_AGENT_PROPOSAL((SELECT PROPOSAL_ID FROM GOVERNANCE_AGENT_PROPOSAL WHERE PROPOSAL_TYPE = 'GAP' AND STATUS = 'REVIEW_REQUIRED' LIMIT 1), 'REJECT', 'Not relevant');

SELECT 'Approval history records' AS CHECK_NAME, COUNT(*) AS N FROM GOVERNANCE_APPROVAL_HISTORY;
SELECT 'Dashboard unchanged after review' AS CHECK_NAME, COUNT(DISTINCT GAP_ID) AS N FROM V_READINESSOPS_ACTION_BOARD WHERE GAP_ID IS NOT NULL;

-- TEST 4: Controlled publication
SELECT '--- TEST 4: CONTROLLED PUBLICATION ---' AS TEST;
CALL SP_PUBLISH_AGENT_RUN((SELECT AGENT_RUN_ID FROM GOVERNANCE_AGENT_RUN ORDER BY CREATED_AT DESC LIMIT 1));
SELECT 'Published proposals' AS CHECK_NAME, COUNT(*) AS N FROM GOVERNANCE_AGENT_PROPOSAL WHERE STATUS = 'PUBLISHED';
SELECT 'Rejected proposals (should remain)' AS CHECK_NAME, COUNT(*) AS N FROM GOVERNANCE_AGENT_PROPOSAL WHERE STATUS = 'REJECTED';
SELECT 'New canonical gaps from publish' AS CHECK_NAME, COUNT(*) AS N FROM READINESS_GAPS WHERE GAP_ID LIKE 'PUB_%';
SELECT 'Dashboard now shows published' AS CHECK_NAME, COUNT(DISTINCT GAP_ID) AS N FROM V_READINESSOPS_ACTION_BOARD WHERE GAP_ID LIKE 'PUB_%';

-- TEST 5: History preservation
SELECT '--- TEST 5: HISTORY PRESERVATION ---' AS TEST;
CALL SP_RUN_FULL_GOVERNANCE_REVIEW('RUN_001', 'Second run test');
SELECT 'Total agent runs (should be 2+)' AS CHECK_NAME, COUNT(*) AS N FROM GOVERNANCE_AGENT_RUN;
SELECT 'Previous proposals preserved' AS CHECK_NAME, COUNT(*) AS N FROM GOVERNANCE_AGENT_PROPOSAL WHERE AGENT_RUN_ID != (SELECT AGENT_RUN_ID FROM GOVERNANCE_AGENT_RUN ORDER BY CREATED_AT DESC LIMIT 1);

-- TEST 6: Verify no REVIEW_REQUIRED in dashboard
SELECT '--- TEST 6: DASHBOARD SAFETY ---' AS TEST;
SELECT 'REVIEW_REQUIRED proposals NOT in dashboard' AS CHECK_NAME, 0 AS EXPECTED,
    (SELECT COUNT(*) FROM V_READINESSOPS_ACTION_BOARD WHERE GAP_ID IN (SELECT 'PUB_' || PROPOSAL_ID FROM GOVERNANCE_AGENT_PROPOSAL WHERE STATUS = 'REVIEW_REQUIRED')) AS ACTUAL;
