USE DATABASE READINESSOPS_VALIDATION;
USE SCHEMA APP;

SELECT '1_WORKSPACE_OBJECTS' AS TEST_NAME,
       COUNT_IF(PROCEDURE_NAME = 'SP_RUN_FULL_GOVERNANCE_REVIEW') AS FULL_REVIEW_PROC,
       COUNT_IF(PROCEDURE_NAME = 'SP_REVIEW_AGENT_PROPOSAL') AS REVIEW_PROC,
       COUNT_IF(PROCEDURE_NAME = 'SP_PUBLISH_AGENT_RUN') AS PUBLISH_PROC
FROM INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'APP'
  AND PROCEDURE_NAME IN (
    'SP_RUN_FULL_GOVERNANCE_REVIEW',
    'SP_REVIEW_AGENT_PROPOSAL',
    'SP_PUBLISH_AGENT_RUN'
  );

SELECT '2_PROPOSAL_STATUS' AS TEST_NAME,
       PROPOSAL_TYPE,
       STATUS,
       COUNT(*) AS RECORD_COUNT
FROM GOVERNANCE_AGENT_PROPOSAL
GROUP BY PROPOSAL_TYPE, STATUS
ORDER BY PROPOSAL_TYPE, STATUS;

SELECT '3_REVIEW_HISTORY' AS TEST_NAME,
       ACTION_TYPE,
       COUNT(*) AS RECORD_COUNT
FROM GOVERNANCE_APPROVAL_HISTORY
GROUP BY ACTION_TYPE
ORDER BY ACTION_TYPE;

SELECT '4_PUBLISHED_TRACEABILITY' AS TEST_NAME,
       p.PROPOSAL_ID,
       p.PROPOSAL_TYPE,
       p.STATUS,
       p.PUBLISHED_ENTITY_ID,
       CASE
         WHEN p.PROPOSAL_TYPE IN ('GAP', 'RISK') THEN
           IFF(EXISTS (
             SELECT 1
             FROM READINESS_GAPS g
             WHERE g.SOURCE_PROPOSAL_ID = p.PROPOSAL_ID
           ), 'OK', 'MISSING')
         WHEN p.PROPOSAL_TYPE = 'ACTION' THEN
           IFF(EXISTS (
             SELECT 1
             FROM RECOMMENDED_ACTIONS a
             WHERE a.SOURCE_PROPOSAL_ID = p.PROPOSAL_ID
           ), 'OK', 'MISSING')
         ELSE 'UNKNOWN'
       END AS CANONICAL_STATUS
FROM GOVERNANCE_AGENT_PROPOSAL p
WHERE p.STATUS = 'PUBLISHED'
ORDER BY p.PROPOSAL_TYPE, p.PROPOSAL_ID;

SELECT '5_DUPLICATE_CANONICAL' AS TEST_NAME,
       SOURCE_PROPOSAL_ID,
       COUNT(*) AS RECORD_COUNT
FROM (
  SELECT SOURCE_PROPOSAL_ID FROM READINESS_GAPS
  WHERE SOURCE_PROPOSAL_ID IS NOT NULL
  UNION ALL
  SELECT SOURCE_PROPOSAL_ID FROM RECOMMENDED_ACTIONS
  WHERE SOURCE_PROPOSAL_ID IS NOT NULL
)
GROUP BY SOURCE_PROPOSAL_ID
HAVING COUNT(*) > 1;

SELECT '6_DUPLICATE_PUBLISH_HISTORY' AS TEST_NAME,
       PROPOSAL_ID,
       COUNT(*) AS RECORD_COUNT
FROM GOVERNANCE_APPROVAL_HISTORY
WHERE ACTION_TYPE = 'PUBLISH'
GROUP BY PROPOSAL_ID
HAVING COUNT(*) > 1;

SELECT '7_DASHBOARD_SAFETY' AS TEST_NAME,
       COUNT_IF(GAP_ID LIKE 'AR_%') AS LEGACY_GAPS_VISIBLE,
       COUNT_IF(ACTION_ID LIKE 'AR_%') AS LEGACY_ACTIONS_VISIBLE,
       COUNT_IF(GAP_ID LIKE 'PUB_%') AS PUBLISHED_ROWS_VISIBLE
FROM V_READINESSOPS_ACTION_BOARD;
