-- ReadinessOps finalist validation
-- Read-only checks. No application data is modified.

USE ROLE ACCOUNTADMIN;
USE DATABASE READINESSOPS_VALIDATION;
USE SCHEMA APP;
USE WAREHOUSE READINESSOPS_WH;

-- 1. Required procedures, including the finalist Decision Pack path.
SELECT
    '1_REQUIRED_PROCEDURES' AS TEST_NAME,
    MAX(IFF(PROCEDURE_NAME = 'SP_RUN_FULL_GOVERNANCE_REVIEW', 1, 0)) AS LEGACY_REVIEW,
    MAX(IFF(PROCEDURE_NAME = 'SP_REVIEW_AGENT_PROPOSAL', 1, 0)) AS HUMAN_DECISION,
    MAX(IFF(PROCEDURE_NAME = 'SP_PUBLISH_AGENT_RUN', 1, 0)) AS CONTROLLED_PUBLISH,
    MAX(IFF(PROCEDURE_NAME = 'SP_GENERATE_DECISION_PACK', 1, 0)) AS DECISION_PACK,
    MAX(IFF(PROCEDURE_NAME = 'SP_EDIT_AGENT_PROPOSAL', 1, 0)) AS PROPOSAL_EDIT
FROM INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'APP'
  AND PROCEDURE_NAME IN (
      'SP_RUN_FULL_GOVERNANCE_REVIEW',
      'SP_REVIEW_AGENT_PROPOSAL',
      'SP_PUBLISH_AGENT_RUN',
      'SP_GENERATE_DECISION_PACK',
      'SP_EDIT_AGENT_PROPOSAL'
  );

-- 2. Required finalist data objects.
SELECT
    '2_REQUIRED_OBJECTS' AS TEST_NAME,
    IFF(EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = 'APP' AND TABLE_NAME = 'AI_INITIATIVE'
    ), 1, 0) AS AI_INITIATIVE,
    IFF(EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = 'APP' AND TABLE_NAME = 'GOVERNED_DECISION_RECORD'
    ), 1, 0) AS GOVERNED_DECISION_RECORD,
    IFF(EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.TABLES
        WHERE TABLE_SCHEMA = 'APP' AND TABLE_NAME = 'GOVERNANCE_AGENT_RUN_STEP'
    ), 1, 0) AS GOVERNANCE_AGENT_RUN_STEP,
    IFF(EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.VIEWS
        WHERE TABLE_SCHEMA = 'APP' AND TABLE_NAME = 'V_AI_PORTFOLIO'
    ), 1, 0) AS AI_PORTFOLIO_VIEW,
    IFF(EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.STAGES
        WHERE STAGE_SCHEMA = 'APP' AND STAGE_NAME = 'READINESSOPS_EVIDENCE_STAGE'
    ), 1, 0) AS EVIDENCE_STAGE;

-- 3. Latest completed run traceability. Question and rule references are
-- required for legacy proposals; Decision Pack proposals use evidence IDs.
WITH LATEST AS (
    SELECT AGENT_RUN_ID
    FROM GOVERNANCE_AGENT_RUN
    WHERE STATUS = 'COMPLETED'
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ASSESSMENT_RUN_ID, WORKFLOW_TYPE
        ORDER BY COMPLETED_AT DESC, CREATED_AT DESC
    ) = 1
)
SELECT
    '3_LATEST_RUN_TRACEABILITY' AS TEST_NAME,
    COUNT(*) AS TOTAL_PROPOSALS,
    COUNT_IF(s.PROPOSAL_ID IS NULL) AS MISSING_SOURCE_ROWS,
    COUNT_IF(
        p.PROPOSAL_TYPE IN ('GAP', 'RISK', 'ACTION')
        AND s.QUESTION_ID IS NULL
    ) AS MISSING_LEGACY_QUESTION,
    COUNT_IF(s.EVIDENCE_ITEM_ID IS NULL) AS MISSING_EVIDENCE_REFERENCE,
    COUNT_IF(
        p.PROPOSAL_TYPE IN ('GAP', 'RISK', 'ACTION')
        AND s.RULE_ID IS NULL
    ) AS MISSING_LEGACY_RULE
FROM GOVERNANCE_AGENT_PROPOSAL p
JOIN LATEST l
  ON p.AGENT_RUN_ID = l.AGENT_RUN_ID
LEFT JOIN GOVERNANCE_AGENT_PROPOSAL_SOURCE s
  ON p.PROPOSAL_ID = s.PROPOSAL_ID;

-- 4. Proposal state distribution.
SELECT
    '4_PROPOSAL_STATE' AS TEST_NAME,
    PROPOSAL_TYPE,
    STATUS,
    COUNT(*) AS RECORD_COUNT
FROM GOVERNANCE_AGENT_PROPOSAL
GROUP BY PROPOSAL_TYPE, STATUS
ORDER BY PROPOSAL_TYPE, STATUS;

-- 5. Human approval and publication attribution.
SELECT
    '5_AUDIT_COMPLETENESS' AS TEST_NAME,
    ACTION_TYPE,
    COUNT(*) AS RECORD_COUNT,
    COUNT_IF(ACTED_BY IS NULL) AS MISSING_ACTOR,
    COUNT_IF(ACTED_AT IS NULL) AS MISSING_TIME
FROM GOVERNANCE_APPROVAL_HISTORY
GROUP BY ACTION_TYPE
ORDER BY ACTION_TYPE;

-- 6. A proposal may produce at most one canonical governed record.
SELECT
    '6_DUPLICATE_CANONICAL_RECORDS' AS TEST_NAME,
    SOURCE_PROPOSAL_ID,
    COUNT(*) AS RECORD_COUNT
FROM (
    SELECT SOURCE_PROPOSAL_ID FROM READINESS_GAPS
    WHERE SOURCE_PROPOSAL_ID IS NOT NULL
    UNION ALL
    SELECT SOURCE_PROPOSAL_ID FROM RECOMMENDED_ACTIONS
    WHERE SOURCE_PROPOSAL_ID IS NOT NULL
    UNION ALL
    SELECT SOURCE_PROPOSAL_ID FROM GOVERNED_DECISION_RECORD
    WHERE SOURCE_PROPOSAL_ID IS NOT NULL
)
GROUP BY SOURCE_PROPOSAL_ID
HAVING COUNT(*) > 1;

-- 7. Publication history is idempotent per proposal.
SELECT
    '7_DUPLICATE_PUBLISH_HISTORY' AS TEST_NAME,
    PROPOSAL_ID,
    COUNT(*) AS RECORD_COUNT
FROM GOVERNANCE_APPROVAL_HISTORY
WHERE ACTION_TYPE = 'PUBLISH'
GROUP BY PROPOSAL_ID
HAVING COUNT(*) > 1;

-- 8. Every published proposal resolves to its correct governed table.
SELECT
    '8_PUBLISHED_TRACEABILITY' AS TEST_NAME,
    p.PROPOSAL_TYPE,
    COUNT(*) AS PUBLISHED_PROPOSALS,
    COUNT_IF(p.PUBLISHED_ENTITY_ID IS NULL) AS MISSING_ENTITY_ID,
    COUNT_IF(
        CASE
            WHEN p.PROPOSAL_TYPE IN ('GAP', 'RISK') THEN
                NOT EXISTS (
                    SELECT 1 FROM READINESS_GAPS g
                    WHERE g.SOURCE_PROPOSAL_ID = p.PROPOSAL_ID
                )
            WHEN p.PROPOSAL_TYPE = 'ACTION' THEN
                NOT EXISTS (
                    SELECT 1 FROM RECOMMENDED_ACTIONS a
                    WHERE a.SOURCE_PROPOSAL_ID = p.PROPOSAL_ID
                )
            WHEN p.PROPOSAL_TYPE LIKE 'DECISION_%' THEN
                NOT EXISTS (
                    SELECT 1 FROM GOVERNED_DECISION_RECORD d
                    WHERE d.SOURCE_PROPOSAL_ID = p.PROPOSAL_ID
                )
            ELSE TRUE
        END
    ) AS MISSING_GOVERNED_RECORD
FROM GOVERNANCE_AGENT_PROPOSAL p
WHERE p.STATUS = 'PUBLISHED'
GROUP BY p.PROPOSAL_TYPE
ORDER BY p.PROPOSAL_TYPE;

-- 9. Uploaded evidence has original-file and parser metadata.
SELECT
    '9_EVIDENCE_RETENTION' AS TEST_NAME,
    SOURCE_TYPE,
    COUNT(*) AS EVIDENCE_ITEMS,
    COUNT_IF(STAGE_PATH IS NULL) AS MISSING_STAGE_PATH,
    COUNT_IF(CONTENT_SHA256 IS NULL) AS MISSING_SHA256,
    COUNT_IF(
        SOURCE_TYPE = 'UPLOADED_PDF'
        AND (PARSER_NAME IS NULL OR PAGE_COUNT IS NULL)
    ) AS MISSING_PDF_METADATA
FROM EVIDENCE_ITEMS
WHERE SOURCE_TYPE IN ('UPLOADED_TXT', 'UPLOADED_PDF')
GROUP BY SOURCE_TYPE
ORDER BY SOURCE_TYPE;

-- 10. Traced Decision Pack runs contain the exact governed step contract.
WITH TRACED_RUNS AS (
    SELECT AGENT_RUN_ID
    FROM GOVERNANCE_AGENT_RUN_STEP
    GROUP BY AGENT_RUN_ID
)
SELECT
    '10_AGENT_EXECUTION_TRACE' AS TEST_NAME,
    r.AGENT_RUN_ID,
    COUNT(s.AGENT_RUN_STEP_ID) AS RECORDED_STEPS,
    COUNT_IF(s.STATUS = 'COMPLETED') AS COMPLETED_STEPS,
    COUNT_IF(s.STATUS = 'RUNNING') AS RUNNING_STEPS,
    COUNT_IF(s.STATUS = 'FAILED') AS FAILED_STEPS,
    COUNT(DISTINCT s.STEP_CODE) AS DISTINCT_STEP_CODES,
    COUNT_IF(s.STARTED_AT IS NULL) AS MISSING_START_TIME,
    COUNT_IF(
        s.STATUS IN ('COMPLETED', 'FAILED')
        AND s.COMPLETED_AT IS NULL
    ) AS MISSING_END_TIME
FROM GOVERNANCE_AGENT_RUN r
JOIN TRACED_RUNS t
  ON r.AGENT_RUN_ID = t.AGENT_RUN_ID
JOIN GOVERNANCE_AGENT_RUN_STEP s
  ON r.AGENT_RUN_ID = s.AGENT_RUN_ID
WHERE r.WORKFLOW_TYPE = 'DECISION_PACK'
GROUP BY r.AGENT_RUN_ID
ORDER BY MAX(r.CREATED_AT) DESC;

SHOW STREAMLITS LIKE 'READINESSOPS_DASHBOARD'
    IN SCHEMA READINESSOPS_VALIDATION.APP;

SELECT
    '11_PRODUCTION_STREAMLIT' AS TEST_NAME,
    "name" AS STREAMLIT_NAME,
    "query_warehouse" AS QUERY_WAREHOUSE,
    "owner" AS OWNER,
    "created_on" AS CREATED_ON
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE UPPER("name") = 'READINESSOPS_DASHBOARD';

SHOW STREAMLITS IN SCHEMA READINESSOPS_VALIDATION.APP;

SELECT
    '12_HACKATHON_ONLY_OBJECTS_REMOVED' AS TEST_NAME,
    COUNT_IF(
        UPPER("name") IN (
            'READINESSOPS_DASHBOARD_HACKATHON_DEV',
            'READINESSOPS_GOVERNANCE_REVIEW'
        )
    ) AS HACKATHON_ONLY_STREAMLITS_REMAINING
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));
