-- ReadinessOps Hackathon Final Validation
-- Read-only checks. No application data is modified.

USE ROLE ACCOUNTADMIN;
USE DATABASE READINESSOPS_VALIDATION;
USE SCHEMA APP;
USE WAREHOUSE READINESSOPS_WH;

SELECT
    '1_REQUIRED_PROCEDURES' AS TEST_NAME,
    COUNT_IF(PROCEDURE_NAME = 'SP_RUN_FULL_GOVERNANCE_REVIEW') AS REVIEW_GENERATION,
    COUNT_IF(PROCEDURE_NAME = 'SP_REVIEW_AGENT_PROPOSAL') AS HUMAN_DECISION,
    COUNT_IF(PROCEDURE_NAME = 'SP_PUBLISH_AGENT_RUN') AS CONTROLLED_PUBLISH
FROM INFORMATION_SCHEMA.PROCEDURES
WHERE PROCEDURE_SCHEMA = 'APP'
  AND PROCEDURE_NAME IN (
      'SP_RUN_FULL_GOVERNANCE_REVIEW',
      'SP_REVIEW_AGENT_PROPOSAL',
      'SP_PUBLISH_AGENT_RUN'
  );

WITH LATEST AS (
    SELECT AGENT_RUN_ID
    FROM GOVERNANCE_AGENT_RUN
    WHERE STATUS = 'COMPLETED'
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY ASSESSMENT_RUN_ID
        ORDER BY COMPLETED_AT DESC, CREATED_AT DESC
    ) = 1
)
SELECT
    '2_LATEST_RUN_TRACEABILITY' AS TEST_NAME,
    COUNT(*) AS TOTAL_PROPOSALS,
    COUNT_IF(s.PROPOSAL_ID IS NULL) AS MISSING_SOURCE_ROWS,
    COUNT_IF(s.QUESTION_ID IS NULL) AS MISSING_QUESTION,
    COUNT_IF(s.EVIDENCE_ITEM_ID IS NULL) AS MISSING_EVIDENCE_REFERENCE,
    COUNT_IF(s.RULE_ID IS NULL) AS MISSING_RULE_REFERENCE
FROM GOVERNANCE_AGENT_PROPOSAL p
JOIN LATEST l
  ON p.AGENT_RUN_ID = l.AGENT_RUN_ID
LEFT JOIN GOVERNANCE_AGENT_PROPOSAL_SOURCE s
  ON p.PROPOSAL_ID = s.PROPOSAL_ID;

SELECT
    '3_PROPOSAL_STATE' AS TEST_NAME,
    PROPOSAL_TYPE,
    STATUS,
    COUNT(*) AS RECORD_COUNT
FROM GOVERNANCE_AGENT_PROPOSAL
GROUP BY PROPOSAL_TYPE, STATUS
ORDER BY PROPOSAL_TYPE, STATUS;

SELECT
    '4_AUDIT_COMPLETENESS' AS TEST_NAME,
    ACTION_TYPE,
    COUNT(*) AS RECORD_COUNT,
    COUNT_IF(ACTED_BY IS NULL) AS MISSING_ACTOR,
    COUNT_IF(ACTED_AT IS NULL) AS MISSING_TIME
FROM GOVERNANCE_APPROVAL_HISTORY
GROUP BY ACTION_TYPE
ORDER BY ACTION_TYPE;

SELECT
    '5_DUPLICATE_CANONICAL_RECORDS' AS TEST_NAME,
    SOURCE_PROPOSAL_ID,
    COUNT(*) AS RECORD_COUNT
FROM (
    SELECT SOURCE_PROPOSAL_ID
    FROM READINESS_GAPS
    WHERE SOURCE_PROPOSAL_ID IS NOT NULL
    UNION ALL
    SELECT SOURCE_PROPOSAL_ID
    FROM RECOMMENDED_ACTIONS
    WHERE SOURCE_PROPOSAL_ID IS NOT NULL
)
GROUP BY SOURCE_PROPOSAL_ID
HAVING COUNT(*) > 1;

SELECT
    '6_DUPLICATE_PUBLISH_HISTORY' AS TEST_NAME,
    PROPOSAL_ID,
    COUNT(*) AS RECORD_COUNT
FROM GOVERNANCE_APPROVAL_HISTORY
WHERE ACTION_TYPE = 'PUBLISH'
GROUP BY PROPOSAL_ID
HAVING COUNT(*) > 1;

SELECT
    '7_PUBLISHED_TRACEABILITY' AS TEST_NAME,
    p.PROPOSAL_TYPE,
    COUNT(*) AS PUBLISHED_PROPOSALS,
    COUNT_IF(p.PUBLISHED_ENTITY_ID IS NULL) AS MISSING_ENTITY_ID,
    COUNT_IF(
        CASE
            WHEN p.PROPOSAL_TYPE IN ('GAP', 'RISK') THEN
                NOT EXISTS (
                    SELECT 1
                    FROM READINESS_GAPS g
                    WHERE g.SOURCE_PROPOSAL_ID = p.PROPOSAL_ID
                )
            WHEN p.PROPOSAL_TYPE = 'ACTION' THEN
                NOT EXISTS (
                    SELECT 1
                    FROM RECOMMENDED_ACTIONS a
                    WHERE a.SOURCE_PROPOSAL_ID = p.PROPOSAL_ID
                )
            ELSE TRUE
        END
    ) AS MISSING_CANONICAL_RECORD
FROM GOVERNANCE_AGENT_PROPOSAL p
WHERE p.STATUS = 'PUBLISHED'
GROUP BY p.PROPOSAL_TYPE
ORDER BY p.PROPOSAL_TYPE;

SHOW STREAMLITS LIKE 'READINESSOPS_GOVERNANCE_REVIEW'
    IN SCHEMA READINESSOPS_VALIDATION.APP;

SELECT
    '8_FINAL_STREAMLIT_OBJECT' AS TEST_NAME,
    "name" AS STREAMLIT_NAME,
    "query_warehouse" AS QUERY_WAREHOUSE,
    "owner" AS OWNER,
    "created_on" AS CREATED_ON
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE UPPER("name") = 'READINESSOPS_GOVERNANCE_REVIEW';

SHOW STREAMLITS LIKE 'READINESSOPS_DASHBOARD'
    IN SCHEMA READINESSOPS_VALIDATION.APP;

SELECT
    '9_EXISTING_APP_RETAINED' AS TEST_NAME,
    COUNT(*) AS EXISTING_APP_COUNT
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE UPPER("name") = 'READINESSOPS_DASHBOARD';
