-- ============================================================
-- Revision Lifecycle Foundation Validation
-- ============================================================
-- Read-only validation. Expected FAIL_COUNT is zero for every row.
-- Safe before and after existing-run migration.
-- ============================================================

USE SCHEMA APP;

SELECT '1_DUPLICATE_CASE_ID' AS TEST_NAME, COUNT(*) AS FAIL_COUNT
FROM (
    SELECT CASE_ID
    FROM ASSESSMENT_CASE
    GROUP BY CASE_ID
    HAVING COUNT(*) > 1
)
UNION ALL
SELECT '2_DUPLICATE_REVISION_ID', COUNT(*)
FROM (
    SELECT REVISION_ID
    FROM ASSESSMENT_REVISION
    GROUP BY REVISION_ID
    HAVING COUNT(*) > 1
)
UNION ALL
SELECT '3_DUPLICATE_CASE_REVISION_NO', COUNT(*)
FROM (
    SELECT CASE_ID, REVISION_NO
    FROM ASSESSMENT_REVISION
    GROUP BY CASE_ID, REVISION_NO
    HAVING COUNT(*) > 1
)
UNION ALL
SELECT '4_RUN_MAPPED_TO_MULTIPLE_REVISIONS', COUNT(*)
FROM (
    SELECT RUN_ID
    FROM ASSESSMENT_REVISION
    GROUP BY RUN_ID
    HAVING COUNT(*) > 1
)
UNION ALL
SELECT '5_REVISION_WITHOUT_EXISTING_RUN', COUNT(*)
FROM ASSESSMENT_REVISION revision
LEFT JOIN ASSESSMENT_RUNS run
  ON run.RUN_ID = revision.RUN_ID
WHERE run.RUN_ID IS NULL
UNION ALL
SELECT '6_CURRENT_POINTER_NOT_PUBLISHED', COUNT(*)
FROM ASSESSMENT_CASE case_record
LEFT JOIN ASSESSMENT_REVISION revision
  ON revision.REVISION_ID = case_record.CURRENT_REVISION_ID
 AND revision.CASE_ID = case_record.CASE_ID
WHERE case_record.CURRENT_REVISION_ID IS NOT NULL
  AND (
      revision.REVISION_ID IS NULL
      OR revision.STATUS <> 'PUBLISHED'
  )
UNION ALL
SELECT '7_DRAFT_POINTER_NOT_EDITABLE', COUNT(*)
FROM ASSESSMENT_CASE case_record
LEFT JOIN ASSESSMENT_REVISION revision
  ON revision.REVISION_ID = case_record.ACTIVE_DRAFT_REVISION_ID
 AND revision.CASE_ID = case_record.CASE_ID
WHERE case_record.ACTIVE_DRAFT_REVISION_ID IS NOT NULL
  AND (
      revision.REVISION_ID IS NULL
      OR revision.STATUS NOT IN ('DRAFT', 'GENERATING', 'FAILED', 'REVIEW_REQUIRED')
  )
UNION ALL
SELECT '8_CURRENT_AND_DRAFT_POINTER_COLLIDE', COUNT(*)
FROM ASSESSMENT_CASE
WHERE CURRENT_REVISION_ID IS NOT NULL
  AND CURRENT_REVISION_ID = ACTIVE_DRAFT_REVISION_ID
UNION ALL
SELECT '9_MULTIPLE_PENDING_CHANGE_SETS', COUNT(*)
FROM (
    SELECT CASE_ID
    FROM ASSESSMENT_CHANGE_SET
    WHERE STATUS = 'PENDING'
    GROUP BY CASE_ID
    HAVING COUNT(*) > 1
)
UNION ALL
SELECT '10_REVISION_EVIDENCE_RUN_MISMATCH', COUNT(*)
FROM ASSESSMENT_REVISION_EVIDENCE lineage
JOIN ASSESSMENT_REVISION revision
  ON revision.REVISION_ID = lineage.REVISION_ID
LEFT JOIN EVIDENCE_ITEMS evidence
  ON evidence.EVIDENCE_ID = lineage.EVIDENCE_ID
WHERE evidence.EVIDENCE_ID IS NULL
   OR evidence.RUN_ID <> revision.RUN_ID
UNION ALL
SELECT '11_PROPOSAL_LINEAGE_REVISION_MISMATCH', COUNT(*)
FROM GOVERNANCE_PROPOSAL_LINEAGE lineage
JOIN ASSESSMENT_REVISION revision
  ON revision.REVISION_ID = lineage.REVISION_ID
LEFT JOIN GOVERNANCE_AGENT_PROPOSAL proposal
  ON proposal.PROPOSAL_ID = lineage.PROPOSAL_ID
WHERE proposal.PROPOSAL_ID IS NULL
   OR proposal.ASSESSMENT_RUN_ID <> revision.RUN_ID
UNION ALL
SELECT '12_PRODUCTION_DEMO_RESET_ENABLED', COUNT(*)
FROM READINESSOPS_ENVIRONMENT_CONTROL
WHERE ENVIRONMENT_TYPE = 'PRODUCTION'
  AND ALLOW_DEMO_RESET = TRUE
UNION ALL
SELECT '13_ENVIRONMENT_CONTROL_ROW_COUNT',
       IFF(COUNT(*) = 1 AND COUNT_IF(ENVIRONMENT_NAME = CURRENT_DATABASE()) = 1, 0, 1)
FROM READINESSOPS_ENVIRONMENT_CONTROL
UNION ALL
SELECT '14_ENVIRONMENT_CONTROL_TYPE_MISMATCH', COUNT(*)
FROM READINESSOPS_ENVIRONMENT_CONTROL
WHERE ENVIRONMENT_NAME = CURRENT_DATABASE()
  AND ENVIRONMENT_TYPE <> IFF(CURRENT_DATABASE() = 'READINESSOPS_VALIDATION', 'PRODUCTION', 'DEV')
UNION ALL
SELECT '15_NONPRODUCTION_DEMO_RESET_DISABLED', COUNT(*)
FROM READINESSOPS_ENVIRONMENT_CONTROL
WHERE ENVIRONMENT_TYPE IN ('DEV', 'TEST')
  AND ALLOW_DEMO_RESET = FALSE
ORDER BY TEST_NAME;

-- Informational inventory: no expected count.
SELECT
    (SELECT COUNT(*) FROM ASSESSMENT_CASE) AS CASE_COUNT,
    (SELECT COUNT(*) FROM ASSESSMENT_REVISION) AS REVISION_COUNT,
    (SELECT COUNT(*) FROM ASSESSMENT_CASE WHERE CURRENT_REVISION_ID IS NOT NULL) AS CURRENT_CASE_COUNT,
    (SELECT COUNT(*) FROM ASSESSMENT_CASE WHERE ACTIVE_DRAFT_REVISION_ID IS NOT NULL) AS ACTIVE_DRAFT_COUNT,
    (SELECT COUNT(*) FROM ASSESSMENT_CHANGE_SET WHERE STATUS = 'PENDING') AS PENDING_CHANGE_COUNT,
    (SELECT COUNT(*) FROM DATA_PURGE_REQUEST WHERE STATUS <> 'COMPLETED') AS OPEN_PURGE_REQUEST_COUNT;
