-- ============================================================
-- Revision 1 Migration Preview
-- ============================================================
-- Read-only inventory. This script does not create, update, or delete data.
-- Review every candidate before writing the separate migration procedure.
-- ============================================================

USE SCHEMA APP;

WITH RUN_INVENTORY AS (
    SELECT
        run.RUN_ID,
        run.RUN_NAME,
        run.ORGANIZATION_NAME,
        run.ASSESSMENT_SCOPE,
        run.STATUS AS RUN_STATUS,
        run.INITIATIVE_ID,
        run.CREATED_AT,
        (SELECT COUNT(*)
         FROM ASSESSMENT_ANSWERS answer
         WHERE answer.RUN_ID = run.RUN_ID) AS ANSWER_COUNT,
        (SELECT COUNT(*)
         FROM EVIDENCE_ITEMS evidence
         WHERE evidence.RUN_ID = run.RUN_ID) AS EVIDENCE_COUNT,
        (SELECT COUNT(*)
         FROM GOVERNANCE_AGENT_RUN agent_run
         WHERE agent_run.ASSESSMENT_RUN_ID = run.RUN_ID) AS AGENT_RUN_COUNT,
        (SELECT COUNT(*)
         FROM GOVERNANCE_AGENT_PROPOSAL proposal
         WHERE proposal.ASSESSMENT_RUN_ID = run.RUN_ID) AS PROPOSAL_COUNT,
        (SELECT COUNT(*)
         FROM GOVERNANCE_AGENT_PROPOSAL proposal
         WHERE proposal.ASSESSMENT_RUN_ID = run.RUN_ID
           AND proposal.STATUS = 'PUBLISHED') AS PUBLISHED_PROPOSAL_COUNT,
        (SELECT COUNT(*)
         FROM GOVERNANCE_AGENT_PROPOSAL proposal
         WHERE proposal.ASSESSMENT_RUN_ID = run.RUN_ID
           AND proposal.STATUS IN ('REVIEW_REQUIRED', 'APPROVED', 'REJECTED')) AS REVIEWED_OR_PENDING_PROPOSAL_COUNT,
        (SELECT COUNT(*)
         FROM GOVERNED_DECISION_RECORD decision_record
         WHERE decision_record.ASSESSMENT_RUN_ID = run.RUN_ID) AS PUBLISHED_DECISION_COUNT,
        (SELECT COUNT(*)
         FROM READINESS_GAPS gap
         WHERE gap.RUN_ID = run.RUN_ID) AS GAP_COUNT,
        (SELECT COUNT(*)
         FROM RECOMMENDED_ACTIONS action
         WHERE action.RUN_ID = run.RUN_ID) AS ACTION_COUNT
    FROM ASSESSMENT_RUNS run
)
SELECT
    'CASE_' || RUN_ID AS CANDIDATE_CASE_ID,
    'REV_' || RUN_ID AS CANDIDATE_REVISION_ID,
    1 AS CANDIDATE_REVISION_NO,
    RUN_ID,
    RUN_NAME,
    ORGANIZATION_NAME,
    ASSESSMENT_SCOPE,
    RUN_STATUS,
    INITIATIVE_ID,
    CREATED_AT,
    ANSWER_COUNT,
    EVIDENCE_COUNT,
    AGENT_RUN_COUNT,
    PROPOSAL_COUNT,
    PUBLISHED_PROPOSAL_COUNT,
    PUBLISHED_DECISION_COUNT,
    GAP_COUNT,
    ACTION_COUNT,
    CASE
        WHEN PUBLISHED_DECISION_COUNT > 0 OR PUBLISHED_PROPOSAL_COUNT > 0
            THEN 'PUBLISHED'
        WHEN REVIEWED_OR_PENDING_PROPOSAL_COUNT > 0
            THEN 'REVIEW_REQUIRED'
        ELSE 'DRAFT'
    END AS CANDIDATE_REVISION_STATUS,
    CASE
        WHEN PUBLISHED_DECISION_COUNT > 0 OR PUBLISHED_PROPOSAL_COUNT > 0
            THEN 'SET_CURRENT_POINTER'
        ELSE 'SET_ACTIVE_DRAFT_POINTER'
    END AS CANDIDATE_POINTER_ACTION
FROM RUN_INVENTORY
ORDER BY CREATED_AT, RUN_ID;

-- Migration blockers. Every FAIL_COUNT must be zero before migration.
SELECT '1_NULL_RUN_ID' AS TEST_NAME, COUNT(*) AS FAIL_COUNT
FROM ASSESSMENT_RUNS
WHERE RUN_ID IS NULL
UNION ALL
SELECT '2_DUPLICATE_RUN_ID', COUNT(*)
FROM (
    SELECT RUN_ID
    FROM ASSESSMENT_RUNS
    GROUP BY RUN_ID
    HAVING COUNT(*) > 1
)
UNION ALL
SELECT '3_EVIDENCE_WITHOUT_RUN', COUNT(*)
FROM EVIDENCE_ITEMS evidence
LEFT JOIN ASSESSMENT_RUNS run
  ON run.RUN_ID = evidence.RUN_ID
WHERE run.RUN_ID IS NULL
UNION ALL
SELECT '4_PROPOSAL_WITHOUT_RUN', COUNT(*)
FROM GOVERNANCE_AGENT_PROPOSAL proposal
LEFT JOIN ASSESSMENT_RUNS run
  ON run.RUN_ID = proposal.ASSESSMENT_RUN_ID
WHERE run.RUN_ID IS NULL
UNION ALL
SELECT '5_DECISION_WITHOUT_RUN', COUNT(*)
FROM GOVERNED_DECISION_RECORD decision_record
LEFT JOIN ASSESSMENT_RUNS run
  ON run.RUN_ID = decision_record.ASSESSMENT_RUN_ID
WHERE run.RUN_ID IS NULL
UNION ALL
SELECT '6_EXISTING_CASE_ID_COLLISION', COUNT(*)
FROM ASSESSMENT_RUNS run
JOIN ASSESSMENT_CASE case_record
  ON case_record.CASE_ID = 'CASE_' || run.RUN_ID
UNION ALL
SELECT '7_EXISTING_REVISION_ID_COLLISION', COUNT(*)
FROM ASSESSMENT_RUNS run
JOIN ASSESSMENT_REVISION revision
  ON revision.REVISION_ID = 'REV_' || run.RUN_ID
ORDER BY TEST_NAME;
