-- Evidence BINARY storage integrity checks.

USE SCHEMA APP;

SELECT '1_BINARY_METADATA_WITHOUT_OBJECT' AS TEST_NAME, COUNT(*) AS FAIL_COUNT
FROM EVIDENCE_ITEMS evidence
LEFT JOIN EVIDENCE_ORIGINAL_OBJECT original
  ON original.CONTENT_SHA256 = evidence.CONTENT_SHA256
WHERE evidence.STAGE_PATH LIKE 'SNOWFLAKE_BINARY://%'
  AND original.CONTENT_SHA256 IS NULL
UNION ALL
SELECT '2_BINARY_BYTE_COUNT_MISMATCH', COUNT(*)
FROM EVIDENCE_ITEMS evidence
JOIN EVIDENCE_ORIGINAL_OBJECT original
  ON original.CONTENT_SHA256 = evidence.CONTENT_SHA256
WHERE evidence.STAGE_PATH LIKE 'SNOWFLAKE_BINARY://%'
  AND (
      evidence.BYTE_COUNT <> original.BYTE_COUNT
      OR original.BYTE_COUNT <> OCTET_LENGTH(original.FILE_CONTENT)
  )
UNION ALL
SELECT '3_BINARY_STORAGE_PATH_MISMATCH', COUNT(*)
FROM EVIDENCE_ITEMS evidence
WHERE evidence.STAGE_PATH LIKE 'SNOWFLAKE_BINARY://%'
  AND evidence.STAGE_PATH <>
      'SNOWFLAKE_BINARY://EVIDENCE_ORIGINAL_OBJECT/' || evidence.CONTENT_SHA256
ORDER BY TEST_NAME;

SELECT
    revision.REVISION_NO,
    evidence.SOURCE_FILENAME,
    evidence.BYTE_COUNT,
    evidence.PARSER_NAME,
    evidence.STAGE_PATH,
    lineage.SNAPSHOT_ROLE AS REVISION_ROLE
FROM EVIDENCE_ITEMS evidence
LEFT JOIN ASSESSMENT_REVISION revision
  ON revision.RUN_ID = evidence.RUN_ID
LEFT JOIN ASSESSMENT_REVISION_EVIDENCE lineage
  ON lineage.REVISION_ID = revision.REVISION_ID
 AND lineage.EVIDENCE_ID = evidence.EVIDENCE_ID
WHERE evidence.STAGE_PATH LIKE 'SNOWFLAKE_BINARY://%'
ORDER BY evidence.UPLOADED_AT DESC;
