-- ============================================================
-- Evidence Change Impact Analysis Validation
-- ============================================================
-- Read-only checks. Every FAIL_COUNT must be zero.
-- ============================================================

USE SCHEMA APP;

SELECT '1_COMPLETED_RUN_WITHOUT_FOUR_ITEMS' AS TEST_NAME, COUNT(*) AS FAIL_COUNT
FROM (
    SELECT analysis.ANALYSIS_RUN_ID
    FROM REVISION_IMPACT_ANALYSIS_RUN analysis
    LEFT JOIN REVISION_IMPACT_ANALYSIS_ITEM item
      ON item.ANALYSIS_RUN_ID = analysis.ANALYSIS_RUN_ID
     AND item.REVISION_ID = analysis.REVISION_ID
    WHERE analysis.STATUS = 'COMPLETED'
    GROUP BY analysis.ANALYSIS_RUN_ID
    HAVING COUNT(item.IMPACT_ITEM_ID) <> 4
        OR COUNT(DISTINCT item.SECTION_TYPE) <> 4
)
UNION ALL
SELECT '2_INVALID_IMPACT_ENUM', COUNT(*)
FROM REVISION_IMPACT_ANALYSIS_ITEM
WHERE SECTION_TYPE NOT IN (
          'DECISION_GOVERNANCE',
          'DECISION_VALUE',
          'DECISION_MODEL_ROUTING',
          'DECISION_PORTFOLIO'
      )
   OR IMPACT_LEVEL NOT IN ('HIGH', 'MEDIUM', 'LOW', 'NONE')
   OR RECOMMENDED_TREATMENT NOT IN ('REASSESS', 'HUMAN_REVIEW', 'NO_CHANGE')
   OR CONFIDENCE NOT IN ('HIGH', 'MEDIUM', 'LOW')
UNION ALL
SELECT '3_NON_NONE_WITHOUT_CHANGED_EVIDENCE', COUNT(*)
FROM REVISION_IMPACT_ANALYSIS_ITEM
WHERE IMPACT_LEVEL <> 'NONE'
  AND ARRAY_SIZE(SOURCE_EVIDENCE_IDS) = 0
UNION ALL
SELECT '4_NONE_WITH_ACTION_TREATMENT', COUNT(*)
FROM REVISION_IMPACT_ANALYSIS_ITEM
WHERE IMPACT_LEVEL = 'NONE'
  AND RECOMMENDED_TREATMENT <> 'NO_CHANGE'
UNION ALL
SELECT '5_CITATION_OUTSIDE_CHANGED_EVIDENCE', COUNT(*)
FROM REVISION_IMPACT_ANALYSIS_ITEM item,
     LATERAL FLATTEN(INPUT => item.SOURCE_EVIDENCE_IDS) source
WHERE NOT EXISTS (
    SELECT 1
    FROM V_REVISION_EVIDENCE_CHANGE changed
    WHERE changed.REVISION_ID = item.REVISION_ID
      AND changed.EVIDENCE_ID = source.VALUE::VARCHAR
)
UNION ALL
SELECT '6_COMPLETED_RUN_FOR_NON_BASE_REVISION', COUNT(*)
FROM REVISION_IMPACT_ANALYSIS_RUN analysis
JOIN ASSESSMENT_REVISION revision
  ON revision.REVISION_ID = analysis.REVISION_ID
JOIN ASSESSMENT_REVISION base_revision
  ON base_revision.REVISION_ID = analysis.BASE_REVISION_ID
WHERE analysis.STATUS = 'COMPLETED'
  AND (
      revision.BASE_REVISION_ID <> analysis.BASE_REVISION_ID
      OR base_revision.RUN_ID <> analysis.BASE_ASSESSMENT_RUN_ID
  )
UNION ALL
SELECT '7_DUPLICATE_COMPLETED_FINGERPRINT', COUNT(*)
FROM (
    SELECT REVISION_ID, INPUT_FINGERPRINT
    FROM REVISION_IMPACT_ANALYSIS_RUN
    WHERE STATUS = 'COMPLETED'
    GROUP BY REVISION_ID, INPUT_FINGERPRINT
    HAVING COUNT(*) > 1
)
ORDER BY TEST_NAME;

SELECT
    analysis.REVISION_ID,
    analysis.ANALYSIS_RUN_ID,
    analysis.STATUS,
    analysis.MODEL_NAME,
    analysis.PROMPT_VERSION,
    analysis.CHANGED_EVIDENCE_COUNT,
    COUNT(item.IMPACT_ITEM_ID) AS IMPACT_ITEM_COUNT,
    COUNT_IF(item.IMPACT_LEVEL <> 'NONE') AS AFFECTED_SECTION_COUNT,
    COUNT_IF(item.RECOMMENDED_TREATMENT = 'REASSESS') AS REASSESS_SECTION_COUNT,
    analysis.CREATED_BY,
    analysis.COMPLETED_AT
FROM REVISION_IMPACT_ANALYSIS_RUN analysis
LEFT JOIN REVISION_IMPACT_ANALYSIS_ITEM item
  ON item.ANALYSIS_RUN_ID = analysis.ANALYSIS_RUN_ID
 AND item.REVISION_ID = analysis.REVISION_ID
GROUP BY
    analysis.REVISION_ID,
    analysis.ANALYSIS_RUN_ID,
    analysis.STATUS,
    analysis.MODEL_NAME,
    analysis.PROMPT_VERSION,
    analysis.CHANGED_EVIDENCE_COUNT,
    analysis.CREATED_BY,
    analysis.COMPLETED_AT
ORDER BY analysis.COMPLETED_AT DESC NULLS LAST;
